import Head from "next/head"
import Image from "next/image"
import styles from "../../styles/Home.module.css"
import NameTitle from "../NameTitle"
import { motion } from "framer-motion"
import NameAnim from "../NameAnim"
import ScrollInformer from "../ScrollInformer"
import NavBar from "../NavBar"
import Projects from "../projects"
import Details from "./Details"
import Footer from "../footer"
import FAQGrid from "https://framer.com/m/FAQ-Grid-uvJp.js@rbQiKXASeSNS2d01495V"
import { XMarkIcon } from "@heroicons/react/24/outline"
import stagemanager2 from "./images/screen.png"
import frame1 from "./images/frame1.jpg"
import frame2 from "./images/frame2.jpg"
import frame3 from "./images/frame3.jpg" 
import frame4 from "./images/frame4.jpg"
import frame5 from "./images/frame5.jpg"
import frame6 from "./images/frame6.jpg"
import { useEffect } from "react"
import gsap from "gsap"
import { ScrollTrigger } from "gsap/dist/ScrollTrigger"
import Para from "../Para"
import Title from "../title"

const callouts1 = [
    {
        name: "Interviews and Observations",
        description:
            "In the initial phase of user research, we conducted interviews and contextual observations to gather insights and better understand the user's needs and behaviors.",
    },
    {
        name: "Affinity Mapping",
        description:
            "By consolidating and grouping the insights from these interviews and contextual observations, we were able to gain a comprehensive understanding of the user's needs and behaviors.",
    },
    {
        name: "Personas",
        description:
            "Leveraging these insights, we created multiple user personas that highlight their unique needs, goals, and frustrations, using POV (point of view) statements.",
    },
    {
        name: "User Journeys",
        description: "We created individual user journeys that map out current user experiences and pain points. These user journeys enable us to empathize with our users and design solutions that cater to their unique needs and goals.",
    },
]

const callouts2 = [
    {
        name: "Brainstorming",
        description:
            "We conducted a brainstorming session using various ideation techniques such as multiple ideas, worst idea possible, etc, to generate a diverse range of design concepts. After evaluating the ideas based on factors such as feasibility, impact, and user relevance, we selected the best features for the app and organized them into categories.",
    },
    {
        name: "Storyboarding",
        description:
            "To create a compelling vision of how our app could help users in real-world scenarios, we used the insights gathered from user research to develop storyboards. These storyboards depict hypothetical situations and illustrate how users would interact with the app in similar scenarios. This approach allowed us to envision the user experience and refine our design concepts to ensure that they are aligned with the user's needs and goals.",
    },
    {
        name: "Low Fidelity Wireframes",
        description:
        "To facilitate the early stages of the design process and enable quick iterations, we created low-fidelity wireframes on Figma. These wireframes allowed us to explore multiple design concepts quickly and refine them based on user feedback and testing.",
    },
]

const callouts3 = [
    {
        name: "Home Tab",
        description:
            "The Home tab is designed to provide quick access to frequently used features, enabling users to perform commonly used actions with ease. By consolidating the most frequently used functions into one tab, we aim to enhance the user experience by reducing the time and effort required to navigate the app.",
    },
]

export default function Home(): JSX.Element {
    useEffect(() => {
        // gsap.registerPlugin(ScrollTrigger)
        gsap.timeline({}).fromTo(
            "#header",
            { opacity: 0 },
            {
                opacity: 1,
                y: "10px",
                ease: "power1.inOut",
            }
        )
        gsap.to("#header", {
            scale: "0.4",
            height: "400px",
            scrollTrigger: {
                trigger: "#header",
                start: "top top",
                end: "bottom top",
                scrub: true,
            },
        })
        gsap.to(".Projects", {
            color: "black",
        })
    }, [])
    return (
        <div className={styles.container}>
            <Head>
                <title>Vikrant Gurav - KitchenMate</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            <div className="bg-purple-100 innerShadow">
                <main
                    id="header"
                    className="z-0 mx-4 max-w-5xl xl:mx-auto inset-x-0 md:mx-12 lg:mx-24  px-2 py-28 sm:py-32 md:py-28 lg:py-56 flex md:flex-row justify-center flex-col  gap-4"
                >
                    <h1 className="w-full md:w-1/3 my-auto  text-gray-700 text-3xl md:text-5xl align-center font-['SentientItalic']">
                        KitchenMate 
                    </h1>
                    <div className="sm:w-full md:w-2/3">
                        <Image alt="" src={stagemanager2} />
                    </div>
                </main>
            </div>
            <Details />
            <div className=" mx-4 my-5 max-w-5xl xl:mx-auto inset-x-0 md:mx-12 lg:mx-24 px-2">
                <Title text="User Research" />
                <div className="mt-10 mb-10 space-y-12 lg:space-y-0 lg:grid lg:grid-cols-2 lg:gap-x-16 lg:gap-y-8">
                    {callouts1.map((callout) => (
                        <div key={callout.name} className="">
                            <h3 className="text-base font-semibold text-gray-900">
                                <a>
                                    {/* <span className="absolute inset-0" /> */}
                                    {callout.name}
                                </a>
                            </h3>
                            <div className="w-12 h-0.5 my-1.5 rounded-lg bg-gray-400"></div>
                            <p className="mt-1 text-sm text-gray-500">
                                {callout.description}
                            </p>
                        </div>
                    ))}
                </div>
                <Image alt="" src={frame1} />
                <Title text="Conceptual Design" />
                <div className="mt-10 mb-10 space-y-12 lg:space-y-0 lg:grid lg:grid-cols-2 lg:gap-x-16 lg:gap-y-8">
                    {callouts2.map((callout) => (
                        <div key={callout.name} className="">
                            <h3 className="text-base font-semibold text-gray-900">
                                <a>
                                    {/* <span className="absolute inset-0" /> */}
                                    {callout.name}
                                </a>
                            </h3>
                            <div className="w-12 h-0.5 my-1.5 rounded-lg bg-gray-400"></div>
                            <p className="mt-1 text-sm text-gray-500">
                                {callout.description}
                            </p>
                        </div>
                    ))}
                </div>
                <Image alt="" src={frame2} />
                <Title text="Detailed Design" />
                <div className="mt-10 mb-10 space-y-12 lg:space-y-0 lg:grid lg:grid-cols-1 lg:gap-x-16 lg:gap-y-8">
                    {callouts3.map((callout) => (
                        <div key={callout.name} className="">
                            <h3 className="text-base font-semibold text-gray-900">
                                <a>
                                    {/* <span className="absolute inset-0" /> */}
                                    {callout.name}
                                </a>
                            </h3>
                            <div className="w-12 h-0.5 my-1.5 rounded-lg bg-gray-400"></div>
                            <p className="mt-1 text-sm text-gray-500">
                                {callout.description}
                            </p>
                        </div>
                    ))}
                </div>
                <Image alt="" src={frame3} />
                <h3 className="text-base mt-20 font-semibold text-gray-900">
                                <a>
                                    {/* <span className="absolute inset-0" /> */}
                                    Recipe Tab
                                </a>
                </h3>
                <div className="w-12 h-0.5 my-1.5 rounded-lg bg-gray-400"></div>
                 <p className="mt-1 text-sm text-gray-500">
                 The Recipe page offers a comprehensive overview of each dish, including a list of ingredients, suggested serving sizes, required equipment, and video tutorials to guide users through each step of the cooking process. Additionally, the app allows users to preview the recipe instructions before beginning to cook, ensuring that they have a clear understanding of the required steps and ingredients.
                </p>
                <Image alt="" src={frame4} />
                <h3 className="text-base mt-20 font-semibold text-gray-900">
                                <a>
                                    {/* <span className="absolute inset-0" /> */}
                                    Recipe Tab - While Cooking
                                </a>
                </h3>
                <div className="w-12 h-0.5 my-1.5 rounded-lg bg-gray-400"></div>
                 <p className="mt-1 mb-10 text-sm text-gray-500">
                 The Recipe page while cooking provides users with a step-by-step guide to cooking a dish, allowing them to easily follow along with the recipe. By presenting detailed instructions in a clear and concise manner, the app aims to make cooking more accessible and enjoyable for users. This feature is particularly useful for novice cooks or those who want to try new recipes but are unfamiliar with certain cooking techniques. The Recipe Detail page also includes helpful tips and tricks to ensure that users achieve the best results possible.
                </p>
                <Image alt="" src={frame5} />
                <div className="mt-20"></div>
                <h3 className="text-base mt-20 font-semibold text-gray-900">
                                <a>
                                    {/* <span className="absolute inset-0" /> */}
                                    Pantry Tab
                                </a>
                </h3>
                <div className="w-12 h-0.5 my-1.5 rounded-lg bg-gray-400"></div>
                 <p className="mt-1 mb-10 text-sm text-gray-500">
                 The Pantry tab allows users to manage the ingredients they have on hand, with expiring items highlighted for easy identification. This feature is especially useful for minimizing food waste and ensuring that users can make the most of the ingredients they have. Based on the ingredients available, the app suggests recipes that users can prepare using the ingredients in their pantry. In addition, the Pantry tab also allows users to add or shop for more ingredients, making it a convenient tool for meal planning and grocery shopping.
                </p>
                <Image alt="" src={frame6} />
                <Title text="Prototype" />
                <div className="mt-10 mb-10 space-y-12 lg:space-y-0 lg:grid lg:grid-cols-2 lg:gap-x-16 lg:gap-y-8">
                </div>
                <iframe  className="rounded-lg border" width="100%" height="700px" src="https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Fproto%2FceIOrE14mSUlIorvNXeeqR%2FUntitled%3Fpage-id%3D0%253A1%26node-id%3D1%253A727%26viewport%3D195%252C448%252C0.08%26scaling%3Dmin-zoom%26starting-point-node-id%3D1%253A727%26show-proto-sidebar%3D1" allowFullScreen ></iframe>
                <Title text="Evaluation" />
                <div className="mt-10 mb-10 space-y-12 lg:space-y-0 lg:grid lg:grid-cols-1 lg:gap-x-16 lg:gap-y-8">
                <p className=" mb-10 text-sm text-gray-500">
                To ensure the effectiveness of our design decisions and validate the usability of our product, we conducted user testing with 6 individuals using the prototype we created in Figma. We chose an in-person testing method to provide a more comprehensive assessment of their interactions with the design elements and to be able to quickly identify any issues or difficulties they encountered in navigating through the product. By doing so, we were able to obtain valuable feedback and insights, enabling us to further refine and improve our design in order to provide an optimal user experience.
                </p>
                </div>
            </div>
            <Footer />
        </div>
    )
}
