import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import NameTitle from "./NameTitle"
import { motion } from "framer-motion"
import NameAnim from "./NameAnim"
import ScrollInformer from "./ScrollInformer"
// import Example from './Example'
import FAQGrid from "https://framer.com/m/FAQ-Grid-uvJp.js@rbQiKXASeSNS2d01495V"

export default function Home(): JSX.Element {
    return (
        <div className={styles.container}>
            <Head>
                <title>Vikrant Gurav</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className="App">
                    <header className="heading">
                        <NameAnim />
                        <NameTitle name="Currently Pursuing my Masters in Human-Computer Interaction" />
                    </header>
                    <ScrollInformer />
                </div>
                <FAQGrid
                    // Using default values:
                    variant="Desktop"
                />
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    )
}
